In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
!pip install chainer

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 10.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for chainer: filename=chainer-7.8.1-py3-none-any.whl size=967716 sha256=a43466872c44be75aae26be888109f89e967d6e5121678c6fa23747287094792
  Stored in directory: /root/.cache/pip/wheels/c4/95/6a/16014db6f761c4e742755b64aac60dbe142da1df6c5919f790
Successfully built chainer


In [ ]:
import chainer

chainer.print_runtime_info()

Platform: Linux-6.1.58+-x86_64-with-glibc2.35
Chainer: 7.8.1
ChainerX: Not Available
NumPy: 1.23.5
CuPy:
  OS                           : Linux-6.1.58+-x86_64-with-glibc2.35
  Python Version               : 3.10.12
  CuPy Version                 : 11.0.0
  CuPy Platform                : NVIDIA CUDA
  NumPy Version                : 1.23.5
  SciPy Version                : 1.11.4
  Cython Build Version         : 0.29.24
  Cython Runtime Version       : 3.0.6
  CUDA Root                    : /usr/local/cuda
  nvcc PATH                    : /usr/local/cuda/bin/nvcc
  CUDA Build Version           : 11070
  CUDA Driver Version          : 12000
  CUDA Runtime Version         : 11080
  cuBLAS Version               : 111103
  cuFFT Version                : 10900
  cuRAND Version               : 10300
  cuSOLVER Version             : (11, 4, 1)
  cuSPARSE Version             : 11705
  NVRTC Version                : (11, 8)
  Thrust Version               : 101500
  CUB Build Version            : 1

In [ ]:
!curl https://colab.chainer.org/install | sh -

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1553  100  1553    0     0   4611      0 --:--:-- --:--:-- --:--:--  4608
********************************************************************************
CUDA version could not be detected!
Try installing Chainer manually by: pip install chainer
********************************************************************************


In [ ]:
# Check CUDA version
!nvcc --version

# Check cuDNN version
!cat /usr/include/cudnn_version.h | grep CUDNN_MAJOR -A 2




nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:33:58_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0
#define CUDNN_MAJOR 8
#define CUDNN_MINOR 9
#define CUDNN_PATCHLEVEL 6
--
#define CUDNN_VERSION (CUDNN_MAJOR * 1000 + CUDNN_MINOR * 100 + CUDNN_PATCHLEVEL)

/* cannot use constexpr here since this is a C-only file */


In [ ]:
!pip install Cmake

In [ ]:
import cupy as cp

In [ ]:
!pip install numpy matplotlib scipy torch opencv-python


In [ ]:
!mkdir models
!wget https://cmu.box.com/shared/static/t1a5u4x6dxohl89104dyrsiz42mvq2sz.pkl -O models/tartanvo_1914.pkl

--2023-12-14 02:12:54--  https://cmu.box.com/shared/static/t1a5u4x6dxohl89104dyrsiz42mvq2sz.pkl
Resolving cmu.box.com (cmu.box.com)... 74.112.186.144
Connecting to cmu.box.com (cmu.box.com)|74.112.186.144|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /public/static/t1a5u4x6dxohl89104dyrsiz42mvq2sz.pkl [following]
--2023-12-14 02:12:55--  https://cmu.box.com/public/static/t1a5u4x6dxohl89104dyrsiz42mvq2sz.pkl
Reusing existing connection to cmu.box.com:443.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://cmu.app.box.com/public/static/t1a5u4x6dxohl89104dyrsiz42mvq2sz.pkl [following]
--2023-12-14 02:12:55--  https://cmu.app.box.com/public/static/t1a5u4x6dxohl89104dyrsiz42mvq2sz.pkl
Resolving cmu.app.box.com (cmu.app.box.com)... 74.112.186.144
Connecting to cmu.app.box.com (cmu.app.box.com)|74.112.186.144|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://public.boxcloud.com/d/1/b

In [ ]:
!mkdir data
!wget https://cmu.box.com/shared/static/nw3bi7x5vng2xy296ndxt19uozpk64jq.zip -O data/KITTI_10.zip
!unzip -q data/KITTI_10.zip -d data/KITTI_10/

--2023-12-14 02:13:09--  https://cmu.box.com/shared/static/nw3bi7x5vng2xy296ndxt19uozpk64jq.zip
Resolving cmu.box.com (cmu.box.com)... 74.112.186.144
Connecting to cmu.box.com (cmu.box.com)|74.112.186.144|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /public/static/nw3bi7x5vng2xy296ndxt19uozpk64jq.zip [following]
--2023-12-14 02:13:09--  https://cmu.box.com/public/static/nw3bi7x5vng2xy296ndxt19uozpk64jq.zip
Reusing existing connection to cmu.box.com:443.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://cmu.app.box.com/public/static/nw3bi7x5vng2xy296ndxt19uozpk64jq.zip [following]
--2023-12-14 02:13:10--  https://cmu.app.box.com/public/static/nw3bi7x5vng2xy296ndxt19uozpk64jq.zip
Resolving cmu.app.box.com (cmu.app.box.com)... 74.112.186.144
Connecting to cmu.app.box.com (cmu.app.box.com)|74.112.186.144|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://public.boxcloud.com/d/1/b

In [ ]:
!mkdir data
!wget https://cmu.box.com/shared/static/1ctocidptdv1xev6pjxdj0b782mrstps.zip -O data/EuRoC_V102.zip
!unzip -q data/EuRoC_V102.zip -d data/EuRoC_V102/

mkdir: cannot create directory ‘data’: File exists
--2023-12-14 02:14:20--  https://cmu.box.com/shared/static/1ctocidptdv1xev6pjxdj0b782mrstps.zip
Resolving cmu.box.com (cmu.box.com)... 74.112.186.144
Connecting to cmu.box.com (cmu.box.com)|74.112.186.144|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /public/static/1ctocidptdv1xev6pjxdj0b782mrstps.zip [following]
--2023-12-14 02:14:21--  https://cmu.box.com/public/static/1ctocidptdv1xev6pjxdj0b782mrstps.zip
Reusing existing connection to cmu.box.com:443.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://cmu.app.box.com/public/static/1ctocidptdv1xev6pjxdj0b782mrstps.zip [following]
--2023-12-14 02:14:21--  https://cmu.app.box.com/public/static/1ctocidptdv1xev6pjxdj0b782mrstps.zip
Resolving cmu.app.box.com (cmu.app.box.com)... 74.112.186.144
Connecting to cmu.app.box.com (cmu.app.box.com)|74.112.186.144|:443... connected.
HTTP request sent, awaiting response... 30

In [ ]:
!python "/content/drive/MyDrive/535/tartanvo/vo_trajectory_from_folder.py"  --model-name tartanvo_1914.pkl \
                                       --kitti \
                                       --batch-size 1 --worker-num 1 \
                                       --test-dir data/KITTI_10/image_left \
                                       --pose-file data/KITTI_10/pose_left.txt

Environment variable DISPLAY is not present in the system.
Switch the backend of matplotlib to agg.
tartanvo_1914.pkl
Does not find any module to load. Try DataParallel version.
Model loaded...
Find 1201 image files in data/KITTI_10/image_left
/usr/local/lib/python3.10/dist-packages/cupy/cuda/compiler.py:460: UserWarning: cupy.cuda.compile_with_cache has been deprecated in CuPy v10, and will be removed in the future. Use cupy.RawModule or cupy.RawKernel instead.
  warnings.warn(
1 Pose inference using 8.843459367752075s: 
[[ 0.1265  0.0143 -0.002  -0.0021  0.001   0.0165]]
2 Pose inference using 0.01941704750061035s: 
[[ 0.1419  0.0179 -0.0026 -0.0028 -0.0002  0.0219]]
3 Pose inference using 0.01928257942199707s: 
[[ 0.1622  0.0282 -0.0019 -0.0018 -0.0008  0.0274]]
4 Pose inference using 0.0218505859375s: 
[[ 0.1766  0.0272 -0.0003  0.0005 -0.0014  0.0345]]
5 Pose inference using 0.02041029930114746s: 
[[ 0.1901  0.0341  0.0047  0.0027 -0.0014  0.039 ]]
6 Pose inference using 0.0191125

In [ ]:
!python "/content/drive/MyDrive/535/tartanvo/vo_trajectory_from_folder.py"  --model-name tartanvo_1914.pkl \
                                       --euroc \
                                       --batch-size 1 --worker-num 1 \
                                       --test-dir data/EuRoC_V102/image_left \
                                       --pose-file data/EuRoC_V102/pose_left.txt

Environment variable DISPLAY is not present in the system.
Switch the backend of matplotlib to agg.
tartanvo_1914.pkl
Does not find any module to load. Try DataParallel version.
Model loaded...
Find 1677 image files in data/EuRoC_V102/image_left
/usr/local/lib/python3.10/dist-packages/cupy/cuda/compiler.py:460: UserWarning: cupy.cuda.compile_with_cache has been deprecated in CuPy v10, and will be removed in the future. Use cupy.RawModule or cupy.RawKernel instead.
  warnings.warn(
1 Pose inference using 1.597318172454834s: 
[[-0.     -0.0001  0.      0.0001  0.0001 -0.0002]]
2 Pose inference using 0.019859790802001953s: 
[[-0.     -0.0001  0.      0.0002  0.0002  0.    ]]
3 Pose inference using 0.019358158111572266s: 
[[-0.      0.0001 -0.     -0.      0.0003  0.0001]]
4 Pose inference using 0.018620729446411133s: 
[[ 0.0006  0.0002 -0.0003  0.0001  0.0002  0.    ]]
5 Pose inference using 0.020287752151489258s: 
[[ 0.0003 -0.0002 -0.0003  0.0001  0.0002  0.0001]]
6 Pose inference using